//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildMentor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildMentor.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string Access_Denied {
            get {
                return ResourceManager.GetString("Access Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Instruction.
        /// </summary>
        public static string Add_Instruction {
            get {
                return ResourceManager.GetString("Add Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Resource.
        /// </summary>
        public static string Add_Resource {
            get {
                return ResourceManager.GetString("Add Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tool.
        /// </summary>
        public static string Add_Tool {
            get {
                return ResourceManager.GetString("Add Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Requests.
        /// </summary>
        public static string Admin_Requests {
            get {
                return ResourceManager.GetString("Admin Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin request denied.
        /// </summary>
        public static string AdminRequestDenied {
            get {
                return ResourceManager.GetString("AdminRequestDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Already_have_an_account_ {
            get {
                return ResourceManager.GetString("Already have an account?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again..
        /// </summary>
        public static string An_error_occurred__Please_try_again_ {
            get {
                return ResourceManager.GetString("An error occurred. Please try again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for admin.
        /// </summary>
        public static string Apply_for_admin {
            get {
                return ResourceManager.GetString("Apply for admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architect.
        /// </summary>
        public static string Architect {
            get {
                return ResourceManager.GetString("Architect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete {
            get {
                return ResourceManager.GetString("Are you sure you want to delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string Billing_Address {
            get {
                return ResourceManager.GetString("Billing Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Birth_Date {
            get {
                return ResourceManager.GetString("Birth Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Tools.
        /// </summary>
        public static string Browse_Tools {
            get {
                return ResourceManager.GetString("Browse Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder.
        /// </summary>
        public static string Builder {
            get {
                return ResourceManager.GetString("Builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpenter.
        /// </summary>
        public static string Carpenter {
            get {
                return ResourceManager.GetString("Carpenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        public static string CEO {
            get {
                return ResourceManager.GetString("CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string Confirm_deletion {
            get {
                return ResourceManager.GetString("Confirm deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Admin Email.
        /// </summary>
        public static string Copy_Admin_Email {
            get {
                return ResourceManager.GetString("Copy Admin Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Message Body.
        /// </summary>
        public static string Copy_Message_Body {
            get {
                return ResourceManager.GetString("Copy Message Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Sender Email.
        /// </summary>
        public static string Copy_Sender_Email {
            get {
                return ResourceManager.GetString("Copy Sender Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        public static string Create_an_Account {
            get {
                return ResourceManager.GetString("Create an Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        public static string Designer {
            get {
                return ResourceManager.GetString("Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        public static string Director {
            get {
                return ResourceManager.GetString("Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Maintenance Document.
        /// </summary>
        public static string Download_Maintenance_Document {
            get {
                return ResourceManager.GetString("Download Maintenance Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Instruction.
        /// </summary>
        public static string Edit_Instruction {
            get {
                return ResourceManager.GetString("Edit Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrician.
        /// </summary>
        public static string Electrician {
            get {
                return ResourceManager.GetString("Electrician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email_Address {
            get {
                return ResourceManager.GetString("Email Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Does not Exist..
        /// </summary>
        public static string Email_Does_not_Exist_ {
            get {
                return ResourceManager.GetString("Email Does not Exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer.
        /// </summary>
        public static string Engineer {
            get {
                return ResourceManager.GetString("Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter approval message.
        /// </summary>
        public static string Enter_approval_message {
            get {
                return ResourceManager.GetString("Enter approval message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter denial message.
        /// </summary>
        public static string Enter_denial_message {
            get {
                return ResourceManager.GetString("Enter denial message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter removal message.
        /// </summary>
        public static string Enter_removal_message {
            get {
                return ResourceManager.GetString("Enter removal message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter request message.
        /// </summary>
        public static string Enter_request_message {
            get {
                return ResourceManager.GetString("Enter request message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter request message and price.
        /// </summary>
        public static string Enter_request_message_and_price {
            get {
                return ResourceManager.GetString("Enter request message and price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Resources.
        /// </summary>
        public static string External_Resources {
            get {
                return ResourceManager.GetString("External Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Resources Count.
        /// </summary>
        public static string External_Resources_Count {
            get {
                return ResourceManager.GetString("External Resources Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Maintenance.
        /// </summary>
        public static string Finish_Maintenance {
            get {
                return ResourceManager.GetString("Finish Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email..
        /// </summary>
        public static string Invalid_Email_ {
            get {
                return ResourceManager.GetString("Invalid Email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscaper.
        /// </summary>
        public static string Landscaper {
            get {
                return ResourceManager.GetString("Landscaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Selection.
        /// </summary>
        public static string Language_Selection {
            get {
                return ResourceManager.GetString("Language Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Maintenance Date.
        /// </summary>
        public static string Last_Maintenance_Date {
            get {
                return ResourceManager.GetString("Last Maintenance Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string Last_Updated {
            get {
                return ResourceManager.GetString("Last Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or Email.
        /// </summary>
        public static string Login_or_Email {
            get {
                return ResourceManager.GetString("Login or Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout failed.
        /// </summary>
        public static string Logout_failed {
            get {
                return ResourceManager.GetString("Logout failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance has been completed..
        /// </summary>
        public static string Maintenance_has_been_completed_ {
            get {
                return ResourceManager.GetString("Maintenance has been completed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance completed.
        /// </summary>
        public static string MantenaceCompleted {
            get {
                return ResourceManager.GetString("MantenaceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mason.
        /// </summary>
        public static string Mason {
            get {
                return ResourceManager.GetString("Mason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanic.
        /// </summary>
        public static string Mechanic {
            get {
                return ResourceManager.GetString("Mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tools.
        /// </summary>
        public static string My_Tools {
            get {
                return ResourceManager.GetString("My Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Replacement.
        /// </summary>
        public static string Needs_Replacement {
            get {
                return ResourceManager.GetString("Needs Replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs maintenance.
        /// </summary>
        public static string NeedsMaintenance {
            get {
                return ResourceManager.GetString("NeedsMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs replacement.
        /// </summary>
        public static string NeedsReplacement {
            get {
                return ResourceManager.GetString("NeedsReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Such Login Exists.
        /// </summary>
        public static string No_Such_Login_Exists {
            get {
                return ResourceManager.GetString("No Such Login Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Signed In.
        /// </summary>
        public static string Not_Signed_In {
            get {
                return ResourceManager.GetString("Not Signed In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications Today.
        /// </summary>
        public static string Notifications_Today {
            get {
                return ResourceManager.GetString("Notifications Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painter.
        /// </summary>
        public static string Painter {
            get {
                return ResourceManager.GetString("Painter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Admin Requests.
        /// </summary>
        public static string Pending_Admin_Requests {
            get {
                return ResourceManager.GetString("Pending Admin Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Tool Permissions.
        /// </summary>
        public static string Pending_Tool_Permissions {
            get {
                return ResourceManager.GetString("Pending Tool Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission removed.
        /// </summary>
        public static string Permission_removed {
            get {
                return ResourceManager.GetString("Permission removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Requests.
        /// </summary>
        public static string Permission_Requests {
            get {
                return ResourceManager.GetString("Permission Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file.
        /// </summary>
        public static string Please_select_a_file {
            get {
                return ResourceManager.GetString("Please select a file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plumber.
        /// </summary>
        public static string Plumber {
            get {
                return ResourceManager.GetString("Plumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Updated Successfully.
        /// </summary>
        public static string Profile_Updated_Successfully {
            get {
                return ResourceManager.GetString("Profile Updated Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Account.
        /// </summary>
        public static string Register_Account {
            get {
                return ResourceManager.GetString("Register Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Date.
        /// </summary>
        public static string Registered_Date {
            get {
                return ResourceManager.GetString("Registered Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string Repeat_Password {
            get {
                return ResourceManager.GetString("Repeat Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request already exists.
        /// </summary>
        public static string Request_already_exists {
            get {
                return ResourceManager.GetString("Request already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request approved..
        /// </summary>
        public static string Request_approved_ {
            get {
                return ResourceManager.GetString("Request approved.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request denied..
        /// </summary>
        public static string Request_denied_ {
            get {
                return ResourceManager.GetString("Request denied.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed.
        /// </summary>
        public static string Request_failed {
            get {
                return ResourceManager.GetString("Request failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Submitted.
        /// </summary>
        public static string Request_Submitted {
            get {
                return ResourceManager.GetString("Request Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Save_Changes {
            get {
                return ResourceManager.GetString("Save Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new status.
        /// </summary>
        public static string Select_new_status {
            get {
                return ResourceManager.GetString("Select new status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set status.
        /// </summary>
        public static string Set_status {
            get {
                return ResourceManager.GetString("Set status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Sign_out {
            get {
                return ResourceManager.GetString("Sign out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status has been updated.
        /// </summary>
        public static string Status_has_been_updated {
            get {
                return ResourceManager.GetString("Status has been updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already in use..
        /// </summary>
        public static string The_email_is_already_in_use_ {
            get {
                return ResourceManager.GetString("The email is already in use.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login is already in use..
        /// </summary>
        public static string The_login_is_already_in_use_ {
            get {
                return ResourceManager.GetString("The login is already in use.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error logging out.
        /// </summary>
        public static string There_was_an_error_logging_out {
            get {
                return ResourceManager.GetString("There was an error logging out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error requesting for Admin.
        /// </summary>
        public static string There_was_an_error_requesting_for_Admin {
            get {
                return ResourceManager.GetString("There was an error requesting for Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Count.
        /// </summary>
        public static string Tool_Count {
            get {
                return ResourceManager.GetString("Tool Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Image.
        /// </summary>
        public static string Tool_Image {
            get {
                return ResourceManager.GetString("Tool Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Name.
        /// </summary>
        public static string Tool_Name {
            get {
                return ResourceManager.GetString("Tool Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Permission Requests.
        /// </summary>
        public static string Tool_Permission_Requests {
            get {
                return ResourceManager.GetString("Tool Permission Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Permissions.
        /// </summary>
        public static string Tool_Permissions {
            get {
                return ResourceManager.GetString("Tool Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Status.
        /// </summary>
        public static string Tool_Status {
            get {
                return ResourceManager.GetString("Tool Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs maintenance.
        /// </summary>
        public static string ToolNeedsMaintenance {
            get {
                return ResourceManager.GetString("ToolNeedsMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool permission removed.
        /// </summary>
        public static string ToolPermissionRemoved {
            get {
                return ResourceManager.GetString("ToolPermissionRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool permission request accepted.
        /// </summary>
        public static string ToolPermissionRequestApproved {
            get {
                return ResourceManager.GetString("ToolPermissionRequestApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool permission request denied.
        /// </summary>
        public static string ToolPermissionRequestDenied {
            get {
                return ResourceManager.GetString("ToolPermissionRequestDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is under maintenance.
        /// </summary>
        public static string ToolUnderMaintenance {
            get {
                return ResourceManager.GetString("ToolUnderMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under maintenance.
        /// </summary>
        public static string UnderMaintenance {
            get {
                return ResourceManager.GetString("UnderMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Tool.
        /// </summary>
        public static string Update_Tool {
            get {
                return ResourceManager.GetString("Update Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed.
        /// </summary>
        public static string Upload_failed {
            get {
                return ResourceManager.GetString("Upload failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload payment document.
        /// </summary>
        public static string Upload_payment_document {
            get {
                return ResourceManager.GetString("Upload payment document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Avatar.
        /// </summary>
        public static string User_Avatar {
            get {
                return ResourceManager.GetString("User Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Count.
        /// </summary>
        public static string User_Count {
            get {
                return ResourceManager.GetString("User Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string User_Management {
            get {
                return ResourceManager.GetString("User Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string User_not_found {
            get {
                return ResourceManager.GetString("User not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string User_Profile {
            get {
                return ResourceManager.GetString("User Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Joined Today.
        /// </summary>
        public static string Users_Joined_Today {
            get {
                return ResourceManager.GetString("Users Joined Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welder.
        /// </summary>
        public static string Welder {
            get {
                return ResourceManager.GetString("Welder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password!.
        /// </summary>
        public static string Wrong_Password_ {
            get {
                return ResourceManager.GetString("Wrong Password!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access this section..
        /// </summary>
        public static string You_don_t_have_permission_to_access_this_section_ {
            get {
                return ResourceManager.GetString("You don\'t have permission to access this section.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been submitted.
        /// </summary>
        public static string Your_request_has_been_submitted {
            get {
                return ResourceManager.GetString("Your request has been submitted", resourceCulture);
            }
        }
    }
}
